import type { Restaurant } from './types';

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'El Rincón del Sabor',
    menu: [
      {
        id: 'starters',
        name: 'Entrantes',
        items: [
          {
            id: '101',
            name: 'Ensalada César',
            description: 'Lechuga romana, aderezo César casero, picatostes y parmesano.',
            price: 9.50,
            allergens: ['gluten', 'fish', 'milk', 'eggs'],
            traces: ['mustard'],
            imageId: 'caesar-salad',
            lastUpdated: '2024-05-20T10:00:00Z',
          },
          {
            id: '102',
            name: 'Croquetas de Jamón Ibérico',
            description: 'Cremosas croquetas caseras con jamón de bellota.',
            price: 12.00,
            allergens: ['gluten', 'milk'],
            traces: ['eggs', 'soybeans'],
            imageId: 'croquetas',
            lastUpdated: '2024-05-21T11:00:00Z',
          },
          {
            id: '103',
            name: 'Gazpacho Andaluz',
            description: 'Sopa fría de tomate y verduras, refrescante y tradicional.',
            price: 8.00,
            allergens: [],
            traces: ['gluten'],
            imageId: 'gazpacho',
            lastUpdated: '2024-05-23T10:00:00Z',
          },
          {
            id: '104',
            name: 'Pulpo a la Gallega',
            description: 'Pulpo cocido con patatas, pimentón y aceite de oliva virgen extra.',
            price: 18.50,
            allergens: ['molluscs'],
            traces: [],
            imageId: 'pulpo-gallega',
            lastUpdated: '2024-05-25T10:00:00Z',
          },
          {
            id: '105',
            name: 'Patatas Bravas',
            description: 'Patatas fritas con salsa brava picante y alioli.',
            price: 7.00,
            allergens: ['eggs', 'milk'],
            traces: ['gluten'],
            imageId: 'patatas-bravas',
            lastUpdated: '2024-05-25T10:30:00Z',
          },
          {
            id: '106',
            name: 'Tabla de Quesos Manchegos',
            description: 'Selección de quesos de oveja con diferentes curaciones, acompañado de membrillo.',
            price: 15.00,
            allergens: ['milk'],
            traces: ['tree-nuts'],
            imageId: 'tabla-quesos',
            lastUpdated: '2024-05-25T11:00:00Z',
          }
        ],
      },
      {
        id: 'mains',
        name: 'Platos Principales',
        items: [
          {
            id: '201',
            name: 'Paella Valenciana',
            description: 'La auténtica paella con pollo, conejo y verduras de la huerta.',
            price: 16.00,
            allergens: [],
            traces: ['molluscs', 'crustaceans'],
            imageId: 'paella-valenciana',
            lastUpdated: '2024-05-22T12:00:00Z',
          },
          {
            id: '202',
            name: 'Solomillo al Roquefort',
            description: 'Tierno solomillo de ternera con una intensa salsa de queso Roquefort.',
            price: 24.50,
            allergens: ['milk'],
            traces: ['celery', 'sulphites'],
            imageId: 'solomillo',
            lastUpdated: '2024-05-22T12:00:00Z',
          },
          {
            id: '203',
            name: 'Merluza en Salsa Verde',
            description: 'Lomos de merluza fresca en una salsa tradicional con almejas.',
            price: 21.00,
            allergens: ['fish', 'molluscs'],
            traces: ['gluten'],
            imageId: 'merluza',
            lastUpdated: '2024-05-21T09:30:00Z',
          },
           {
            id: '204',
            name: 'Cachopo Asturiano',
            description: 'Dos filetes de ternera rellenos de jamón serrano y queso.',
            price: 28.00,
            allergens: ['gluten', 'milk', 'eggs'],
            traces: [],
            imageId: 'cachopo',
            lastUpdated: '2024-05-23T14:00:00Z',
          },
          {
            id: '205',
            name: 'Lubina a la Sal',
            description: 'Pescado entero cocinado en una costra de sal, jugoso y tierno.',
            price: 22.00,
            allergens: ['fish'],
            traces: [],
            imageId: 'lubina-sal',
            lastUpdated: '2024-05-25T12:00:00Z',
          },
          {
            id: '206',
            name: 'Lentejas Estofadas con Chorizo',
            description: 'Guiso tradicional de lentejas con chorizo, panceta y verduras.',
            price: 14.00,
            allergens: [],
            traces: ['celery', 'gluten'],
            imageId: 'lentejas-chorizo',
            lastUpdated: '2024-05-25T12:30:00Z',
          },
          {
            id: '207',
            name: 'Rabo de Toro Estofado',
            description: 'Guiso lento de rabo de toro al vino tinto, tierno y sabroso.',
            price: 23.00,
            allergens: ['sulphites'],
            traces: ['celery', 'gluten'],
            imageId: 'rabo-toro',
            lastUpdated: '2024-05-25T13:00:00Z',
          }
        ],
      },
      {
        id: 'desserts',
        name: 'Postres',
        items: [
          {
            id: '301',
            name: 'Tarta de Queso Casera',
            description: 'Suave y cremosa tarta de queso al horno con base de galleta.',
            price: 7.50,
            allergens: ['gluten', 'eggs', 'milk'],
            traces: ['soybeans', 'tree-nuts'],
            imageId: 'cheesecake',
            lastUpdated: '2024-05-23T15:00:00Z',
          },
          {
            id: '302',
            name: 'Arroz con Leche',
            description: 'Postre tradicional asturiano, cremoso y con un toque de canela.',
            price: 6.00,
            allergens: ['milk'],
            traces: [],
            imageId: 'arroz-con-leche',
            lastUpdated: '2024-05-23T15:00:00Z',
          },
           {
            id: '303',
            name: 'Brownie de Chocolate y Nueces',
            description: 'Intenso brownie de chocolate con nueces, servido con helado de vainilla.',
            price: 8.50,
            allergens: ['gluten', 'eggs', 'milk', 'soybeans', 'tree-nuts'],
            traces: ['peanuts'],
            imageId: 'brownie',
            lastUpdated: '2024-05-24T16:00:00Z',
          },
          {
            id: '304',
            name: 'Crema Catalana',
            description: 'Postre tradicional con base de yema de huevo y azúcar caramelizado.',
            price: 6.50,
            allergens: ['eggs', 'milk'],
            traces: [],
            imageId: 'crema-catalana',
            lastUpdated: '2024-05-25T14:00:00Z',
          },
          {
            id: '305',
            name: 'Tarta de Santiago',
            description: 'Bizcocho de almendra tradicional de Galicia, sin harina.',
            price: 7.00,
            allergens: ['eggs', 'tree-nuts'],
            traces: [],
            imageId: 'tarta-santiago',
            lastUpdated: '2024-05-25T14:30:00Z',
          }
        ],
      },
    ],
  },
];

export function getRestaurantById(id: string): Restaurant | undefined {
  return restaurants.find(r => r.id === id);
}
